# Generated by Django 2.0.3 on 2018-04-04 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeroplane',
            fields=[
                ('aeroplaneid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('manufacturer', models.CharField(max_length=15)),
                ('modelno', models.CharField(max_length=20)),
                ('passengercap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('Monday', models.BooleanField()),
                ('Tuesday', models.BooleanField()),
                ('Wednesday', models.BooleanField()),
                ('Thursday', models.BooleanField()),
                ('Friday', models.BooleanField()),
                ('Saturday', models.BooleanField()),
                ('Sunday', models.BooleanField()),
                ('passengercap', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=4)),
                ('destination', models.CharField(max_length=4)),
                ('arrival', models.TimeField()),
                ('departure', models.TimeField()),
                ('flightid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.Flight')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('flightid', 'source')},
        ),
    ]
